export const SEED_USERS = [
  {
    id: "NsfsgoFIozLMldH1KBGqTlZWeDw2",
    uid: "NsfsgoFIozLMldH1KBGqTlZWeDw2",
    email: "admin@gouujipets.com",
    full_name: "Gouuji Admin",
    role: "admin",
    phone: "+91 98765 00000",
    status: "active",
    created_at: new Date().toISOString()
  },
  {
    id: "partner_dr_sharma",
    uid: "partner_dr_sharma",
    email: "dr.sharma@gouujipets.com",
    full_name: "Dr. Rajesh Sharma",
    role: "partner",
    phone: "+91 98765 11111",
    status: "active",
    created_at: new Date().toISOString()
  },
  {
    id: "partner_anita_rao",
    uid: "partner_anita_rao",
    email: "anita.rao@gouujipets.com",
    full_name: "Anita Rao",
    role: "partner",
    phone: "+91 98765 22222",
    status: "active",
    created_at: new Date().toISOString()
  },
  {
    id: "customer_priya",
    uid: "customer_priya",
    email: "priya.patel@gmail.com",
    full_name: "Priya Patel",
    role: "customer",
    phone: "+91 98765 33333",
    status: "active",
    created_at: new Date().toISOString()
  },
  {
    id: "customer_rahul",
    uid: "customer_rahul",
    email: "rahul.verma@gmail.com",
    full_name: "Rahul Verma",
    role: "customer",
    phone: "+91 98765 44444",
    status: "active",
    created_at: new Date().toISOString()
  }
];

export const SEED_PETS = [
  {
    id: "pet_simba",
    ownerId: "customer_priya",
    name: "Simba",
    type: "dog",
    breed: "Golden Retriever",
    age: "3 years",
    weight: "28 kg",
    gender: "male",
    vaccinated: true,
    microchipped: true,
    photoUrl: "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=600",
    created_at: new Date().toISOString()
  },
  {
    id: "pet_luna",
    ownerId: "customer_priya",
    name: "Luna",
    type: "cat",
    breed: "Persian",
    age: "2 years",
    weight: "4.5 kg",
    gender: "female",
    vaccinated: true,
    microchipped: true,
    photoUrl: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=600",
    created_at: new Date().toISOString()
  },
  {
    id: "pet_max",
    ownerId: "customer_rahul",
    name: "Max",
    type: "dog",
    breed: "German Shepherd",
    age: "4 years",
    weight: "32 kg",
    gender: "male",
    vaccinated: true,
    microchipped: true,
    photoUrl: "https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?auto=format&fit=crop&q=80&w=600",
    created_at: new Date().toISOString()
  }
];

export const SEED_COUPONS = [
  {
    id: "coupon_welcome",
    code: "WELCOME10",
    discount: 10,
    type: "percentage",
    description: "10% off on your first boarding or grooming booking",
    validUntil: "2027-12-31",
    active: true
  },
  {
    id: "coupon_gouuji",
    code: "GOUUJI20",
    discount: 20,
    type: "percentage",
    description: "20% festival special discount on all services",
    validUntil: "2027-12-31",
    active: true
  },
  {
    id: "coupon_pawspa",
    code: "PAWSPA15",
    discount: 15,
    type: "percentage",
    description: "15% off on full spa & grooming packages",
    validUntil: "2027-12-31",
    active: true
  }
];

export const SEED_BUSINESSES = [
  // 1. BOARDING
  {
    id: "biz_boarding_blr_1",
    name: "Paws & Tail Luxury Pet Resort",
    businessName: "Paws & Tail Luxury Pet Resort",
    type: "boarding",
    status: "active",
    rating: 4.9,
    reviews_count: 184,
    reviewCount: 184,
    price_per_night: 1499,
    price_from: 1499,
    base_rate_per_day: 1499,
    priceFrom: 1499,
    address: "12th Main Rd, HAL 2nd Stage, Indiranagar, Bangalore, Karnataka 560038",
    city: "Bangalore",
    lat: 12.9784,
    lng: 77.6408,
    latitude: 12.9784,
    longitude: 77.6408,
    phone: "+91 98765 43210",
    contact_phone: "+91 98765 43210",
    email: "reservations@pawstailresort.com",
    contact_email: "reservations@pawstailresort.com",
    owner_id: "NsfsgoFIozLMldH1KBGqTlZWeDw2",
    capacity: 35,
    open24Hours: true,
    verified: true,
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
    description: "Bangalore's premier luxury boarding facility featuring private temperature-controlled suites, orthopedic bedding, 24/7 CCTV live webcam feeds for parents, and 3 acres of lush grassy play parks with agility courses.",
    image_url: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&q=80&w=1000",
    images: [
      "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1587764379873-97837921fd44?auto=format&fit=crop&q=80&w=1000"
    ],
    services_offered: [
      { id: "deluxe-room", name: "Deluxe AC Room", price: 1499, duration_mins: 1440, description: "Private climate-controlled room with orthopedic bedding, soothing background music, and 24/7 webcam." },
      { id: "luxury-suite", name: "Luxury Villa Suite", price: 2199, duration_mins: 1440, description: "Spacious private suite with personal TV, daily grooming brush, and 3 dedicated 45-min play sessions." },
      { id: "family-suite", name: "Family Suite (Multiple Pets)", price: 2899, duration_mins: 1440, description: "Extra large interconnecting suite designed for siblings with shared bedding and play areas." },
      { id: "day-boarding", name: "Full Day Care & Play", price: 799, duration_mins: 600, description: "10 hours of supervised group play, pool splashing, and wholesome organic snacks." }
    ]
  },
  {
    id: "biz_boarding_mum_1",
    name: "Royal Pet Haven Suite & Camp",
    businessName: "Royal Pet Haven Suite & Camp",
    type: "boarding",
    status: "active",
    rating: 5.0,
    reviews_count: 240,
    reviewCount: 240,
    price_per_night: 2199,
    price_from: 2199,
    base_rate_per_day: 2199,
    priceFrom: 2199,
    address: "Waterfield Rd, Bandra West, Mumbai, Maharashtra 400050",
    city: "Mumbai",
    lat: 19.0596,
    lng: 72.8295,
    latitude: 19.0596,
    longitude: 72.8295,
    phone: "+91 98200 11223",
    contact_phone: "+91 98200 11223",
    email: "stay@royalpethaven.in",
    contact_email: "stay@royalpethaven.in",
    owner_id: "NsfsgoFIozLMldH1KBGqTlZWeDw2",
    capacity: 25,
    open24Hours: true,
    verified: true,
    created_at: new Date(Date.now() - 86400000 * 25).toISOString(),
    description: "Mumbai's most exclusive 5-star boutique pet hotel offering soundproof AC suites, personalized gourmet chef meals, hydrotherapy pool sessions, and round-the-clock veterinary supervision.",
    image_url: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&q=80&w=1000",
    images: [
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1587764379873-97837921fd44?auto=format&fit=crop&q=80&w=1000"
    ],
    services_offered: [
      { id: "luxury-suite", name: "Royal Penthouse Suite", price: 2199, duration_mins: 1440, description: "Top tier soundproof suite with custom orthopedic mattress and daily hydrotherapy session." },
      { id: "executive-suite", name: "Executive Garden Suite", price: 2699, duration_mins: 1440, description: "Includes direct access to a private turf veranda and gourmet tailored nutrition." },
      { id: "weekend-boarding", name: "Weekend Getaway Package", price: 3999, duration_mins: 2880, description: "2 days and 2 nights inclusive of a full spa bath and departure grooming." }
    ]
  },
  {
    id: "biz_boarding_del_1",
    name: "Barkley Manor Boarding & Camp",
    businessName: "Barkley Manor Boarding & Camp",
    type: "boarding",
    status: "active",
    rating: 4.8,
    reviews_count: 156,
    reviewCount: 156,
    price_per_night: 1299,
    price_from: 1299,
    base_rate_per_day: 1299,
    priceFrom: 1299,
    address: "Ring Road, South Extension II, New Delhi, Delhi 110049",
    city: "Delhi",
    lat: 28.5700,
    lng: 77.2200,
    latitude: 28.5700,
    longitude: 77.2200,
    phone: "+91 98111 22334",
    contact_phone: "+91 98111 22334",
    email: "info@barkleymanor.delhi.com",
    contact_email: "info@barkleymanor.delhi.com",
    owner_id: "NsfsgoFIozLMldH1KBGqTlZWeDw2",
    capacity: 40,
    open24Hours: true,
    verified: true,
    created_at: new Date(Date.now() - 86400000 * 20).toISOString(),
    description: "A spacious pet boarding resort in the heart of South Delhi with indoor air-conditioned play arenas, agility training grounds, and round-the-clock trained caregivers.",
    image_url: "https://images.unsplash.com/photo-1587764379873-97837921fd44?auto=format&fit=crop&q=80&w=1000",
    images: [
      "https://images.unsplash.com/photo-1587764379873-97837921fd44?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&q=80&w=1000"
    ],
    services_offered: [
      { id: "standard-room", name: "Standard AC Room", price: 1299, duration_mins: 1440, description: "Comfortable private lodging with 4 daily outdoor leash walks and socialization." },
      { id: "deluxe-room", name: "Deluxe Play Villa", price: 1799, duration_mins: 1440, description: "Enhanced villa with webcam access and complimentary evening treat puzzle." }
    ]
  },
  {
    id: "biz_boarding_pune_1",
    name: "Whispering Pines Pet Camp",
    businessName: "Whispering Pines Pet Camp",
    type: "boarding",
    status: "active",
    rating: 4.9,
    reviews_count: 98,
    reviewCount: 98,
    price_per_night: 1099,
    price_from: 1099,
    base_rate_per_day: 1099,
    priceFrom: 1099,
    address: "North Main Road, Koregaon Park, Pune, Maharashtra 411001",
    city: "Pune",
    lat: 18.5362,
    lng: 73.8939,
    latitude: 18.5362,
    longitude: 73.8939,
    phone: "+91 98220 55667",
    contact_phone: "+91 98220 55667",
    email: "camp@whisperingpines.in",
    contact_email: "camp@whisperingpines.in",
    owner_id: "NsfsgoFIozLMldH1KBGqTlZWeDw2",
    capacity: 30,
    open24Hours: true,
    verified: true,
    created_at: new Date(Date.now() - 86400000 * 15).toISOString(),
    description: "An eco-friendly green pet boarding sanctuary nestled amidst quiet foliage in Koregaon Park. We focus on stress-free natural living, herbal baths, and holistic pet wellness.",
    image_url: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&q=80&w=1000",
    images: [
      "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&q=80&w=1000"
    ],
    services_offered: [
      { id: "standard-room", name: "Eco Cottage Suite", price: 1099, duration_mins: 1440, description: "Natural ventilation cottage with private garden patch and herbal bedding." },
      { id: "ac-room", name: "AC Garden Suite", price: 1499, duration_mins: 1440, description: "Air-conditioned indoor room with garden view and organic meals." }
    ]
  },

  // 2. VETERINARY
  {
    id: "biz_vet_blr_1",
    name: "Gouuji 24/7 Speciality Vet Hospital",
    businessName: "Gouuji 24/7 Speciality Vet Hospital",
    type: "veterinary",
    status: "active",
    rating: 5.0,
    reviews_count: 312,
    reviewCount: 312,
    price_per_night: 799,
    price_from: 799,
    base_rate_per_day: 799,
    priceFrom: 799,
    address: "80 Feet Road, 4th Block, Koramangala, Bangalore, Karnataka 560034",
    city: "Bangalore",
    lat: 12.9352,
    lng: 77.6245,
    latitude: 12.9352,
    longitude: 77.6245,
    phone: "+91 80 4111 2222",
    contact_phone: "+91 80 4111 2222",
    email: "emergency@gouujivet.com",
    contact_email: "emergency@gouujivet.com",
    owner_id: "partner_dr_sharma",
    capacity: 50,
    open24Hours: true,
    verified: true,
    created_at: new Date(Date.now() - 86400000 * 40).toISOString(),
    description: "State-of-the-art 24/7 emergency veterinary hospital equipped with digital X-Ray, color Doppler ultrasound, in-house pathology lab, surgical suites, and ICU oxygen cages.",
    image_url: "https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&q=80&w=1000",
    images: [
      "https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&q=80&w=1000"
    ],
    services_offered: [
      { id: "general-checkup", name: "General Checkup & Consultation", price: 799, duration_mins: 30, description: "Comprehensive nose-to-tail physical exam by senior veterinary physician." },
      { id: "rabies-vaccine", name: "Annual Rabies Vaccination", price: 499, duration_mins: 15, description: "Imported multi-strain rabies vaccination including official health card update." },
      { id: "dhpp-vaccine", name: "DHPP 7-in-1 Vaccination", price: 1199, duration_mins: 20, description: "Complete annual core protection against distemper, parvovirus, and hepatitis." },
      { id: "blood-test", name: "Complete Blood Count (CBC) & Panel", price: 1499, duration_mins: 45, description: "Automated hematology and serum biochemistry profile with 30-min lab reports." },
      { id: "dental-care", name: "Ultrasonic Dental Scaling", price: 2999, duration_mins: 60, description: "Professional ultrasonic teeth cleaning and polishing under sedation." },
      { id: "emergency-consult", name: "24/7 Emergency ICU Care", price: 1999, duration_mins: 60, description: "Immediate triage and emergency critical care intervention." }
    ]
  },
  {
    id: "biz_vet_mum_1",
    name: "PetCare Plus Diagnostics & Surgery",
    businessName: "PetCare Plus Diagnostics & Surgery",
    type: "veterinary",
    status: "active",
    rating: 4.9,
    reviews_count: 275,
    reviewCount: 275,
    price_per_night: 999,
    price_from: 999,
    base_rate_per_day: 999,
    priceFrom: 999,
    address: "Link Road, Lokhandwala Complex, Andheri West, Mumbai, Maharashtra 400053",
    city: "Mumbai",
    lat: 19.1363,
    lng: 72.8277,
    latitude: 19.1363,
    longitude: 72.8277,
    phone: "+91 22 2630 4455",
    contact_phone: "+91 22 2630 4455",
    email: "care@petcareplus.mum.in",
    contact_email: "care@petcareplus.mum.in",
    owner_id: "partner_dr_sharma",
    capacity: 40,
    open24Hours: true,
    verified: true,
    created_at: new Date(Date.now() - 86400000 * 35).toISOString(),
    description: "Mumbai's leading surgical and diagnostic referral veterinary hospital specializing in orthopedic surgery, cardiology echocardiograms, laser therapy, and preventive pet care.",
    image_url: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&q=80&w=1000",
    images: [
      "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&q=80&w=1000"
    ],
    services_offered: [
      { id: "general-checkup", name: "Specialist Consultation", price: 999, duration_mins: 30, description: "Detailed consultation with diagnostic screening recommendations." },
      { id: "ultrasound", name: "Abdominal Ultrasound & Echo", price: 2499, duration_mins: 45, description: "High-resolution color Doppler imaging interpreted by veterinary radiologist." },
      { id: "x-ray", name: "Digital X-Ray (2 Views)", price: 1299, duration_mins: 30, description: "Instant digital radiography for bone fractures and thoracic evaluation." }
    ]
  },
  {
    id: "biz_vet_hyd_1",
    name: "St. Francis Veterinary Clinic & Spa",
    businessName: "St. Francis Veterinary Clinic & Spa",
    type: "veterinary",
    status: "active",
    rating: 4.8,
    reviews_count: 190,
    reviewCount: 190,
    price_per_night: 699,
    price_from: 699,
    base_rate_per_day: 699,
    priceFrom: 699,
    address: "Road No. 36, Jubilee Hills, Hyderabad, Telangana 500033",
    city: "Hyderabad",
    lat: 17.4326,
    lng: 78.4071,
    latitude: 17.4326,
    longitude: 78.4071,
    phone: "+91 40 2355 8899",
    contact_phone: "+91 40 2355 8899",
    email: "clinic@stfrancis.hyd.com",
    contact_email: "clinic@stfrancis.hyd.com",
    owner_id: "partner_dr_sharma",
    capacity: 30,
    open24Hours: false,
    verified: true,
    created_at: new Date(Date.now() - 86400000 * 22).toISOString(),
    description: "A friendly, modern veterinary clinic in Jubilee Hills offering routine wellness exams, vaccinations, microchipping, dietary counseling, and minor surgeries.",
    image_url: "https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&q=80&w=1000",
    images: [
      "https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&q=80&w=1000"
    ],
    services_offered: [
      { id: "general-checkup", name: "General Wellness Checkup", price: 699, duration_mins: 30, description: "Routine health screening and body condition scoring." },
      { id: "deworming", name: "Broad Spectrum Deworming", price: 399, duration_mins: 15, description: "Effective internal parasite treatment tailored to body weight." }
    ]
  },

  // 3. GROOMING
  {
    id: "biz_groom_blr_1",
    name: "The Pampered Paw Spa & Salon",
    businessName: "The Pampered Paw Spa & Salon",
    type: "grooming",
    status: "active",
    rating: 4.9,
    reviews_count: 220,
    reviewCount: 220,
    price_per_night: 999,
    price_from: 999,
    base_rate_per_day: 999,
    priceFrom: 999,
    address: "ITPL Main Rd, Whitefield, Bangalore, Karnataka 560066",
    city: "Bangalore",
    lat: 12.9698,
    lng: 77.7500,
    latitude: 12.9698,
    longitude: 77.7500,
    phone: "+91 98450 66778",
    contact_phone: "+91 98450 66778",
    email: "spa@pamperedpaw.blr.in",
    contact_email: "spa@pamperedpaw.blr.in",
    owner_id: "partner_anita_rao",
    capacity: 20,
    open24Hours: false,
    verified: true,
    created_at: new Date(Date.now() - 86400000 * 28).toISOString(),
    description: "Bangalore's finest luxury styling salon offering organic oatmeal infused baths, breed-specific haircuts, deshedding treatments, pawdicures, and relaxing aromatherapy massages.",
    image_url: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&q=80&w=1000",
    images: [
      "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&q=80&w=1000",
      "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&q=80&w=1000"
    ],
    services_offered: [
      { id: "basic-bath", name: "Refreshing Oatmeal Bath & Blowdry", price: 999, duration_mins: 60, description: "Gentle organic shampoo bath, fluff blowdry, ear cleaning, and nail clipping." },
      { id: "spa-treatment", name: "Full Signature Spa & Styling", price: 1799, duration_mins: 120, description: "Includes deep conditioning mask, breed haircut, sanitary trim, paw balm, and cologne." },
      { id: "deshedding", name: "Intense De-shedding Treatment", price: 1399, duration_mins: 90, description: "Specialized undercoat removal therapy reducing shedding by up to 80%." },
      { id: "nail-trimming", name: "Nail Trimming & Grinding", price: 349, duration_mins: 20, description: "Painless nail shortening and smooth electric grinding." }
    ]
  },
  {
    id: "biz_groom_del_1",
    name: "Furry Styles Studio & Boutique",
    businessName: "Furry Styles Studio & Boutique",
    type: "grooming",
    status: "active",
    rating: 4.9,
    reviews_count: 180,
    reviewCount: 180,
    price_per_night: 1199,
    price_from: 1199,
    base_rate_per_day: 1199,
    priceFrom: 1199,
    address: "Nelson Mandela Marg, Vasant Kunj, New Delhi, Delhi 110070",
    city: "Delhi",
    lat: 28.5300,
    lng: 77.1500,
    latitude: 28.5300,
    longitude: 77.1500,
    phone: "+91 98100 88990",
    contact_phone: "+91 98100 88990",
    email: "studio@furrystyles.delhi.in",
    contact_email: "studio@furrystyles.delhi.in",
    owner_id: "partner_anita_rao",
    capacity: 25,
    open24Hours: false,
    verified: true,
    created_at: new Date(Date.now() - 86400000 * 18).toISOString(),
    description: "A high-end styling boutique in South Delhi staffed by international award-winning groomers. We use 100% vegan, cruelty-free Italian grooming products.",
    image_url: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&q=80&w=1000",
    images: [
      "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&q=80&w=1000"
    ],
    services_offered: [
      { id: "hair-styling", name: "Show-Ring Breed Styling", price: 1999, duration_mins: 120, description: "Precision scissor finishing and standard breed profile styling." },
      { id: "medicated-bath", name: "Medicated Antifungal Bath", price: 1199, duration_mins: 75, description: "Therapeutic bath using prescription veterinary shampoos for itchy skin relief." }
    ]
  },
  {
    id: "biz_groom_chn_1",
    name: "Bubble & Bark Mobile Grooming",
    businessName: "Bubble & Bark Mobile Grooming",
    type: "grooming",
    status: "active",
    rating: 4.8,
    reviews_count: 142,
    reviewCount: 142,
    price_per_night: 899,
    price_from: 899,
    base_rate_per_day: 899,
    priceFrom: 899,
    address: "LB Road, Adyar, Chennai, Tamil Nadu 600020",
    city: "Chennai",
    lat: 13.0012,
    lng: 80.2565,
    latitude: 13.0012,
    longitude: 80.2565,
    phone: "+91 44 2441 5566",
    contact_phone: "+91 44 2441 5566",
    email: "van@bubblebark.chn.in",
    contact_email: "van@bubblebark.chn.in",
    owner_id: "partner_anita_rao",
    capacity: 15,
    open24Hours: false,
    verified: true,
    created_at: new Date(Date.now() - 86400000 * 12).toISOString(),
    description: "Chennai's favorite doorstep mobile grooming spa van! We bring a fully equipped, air-conditioned luxury grooming studio right to your driveway for zero travel stress.",
    image_url: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&q=80&w=1000",
    images: [
      "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&q=80&w=1000"
    ],
    services_offered: [
      { id: "basic-bath", name: "Doorstep Spa Bath & Fluff", price: 899, duration_mins: 60, description: "Complete bath and dry inside our climate-controlled grooming van at your doorstep." },
      { id: "hair-trimming", name: "Full Doorstep Groom & Haircut", price: 1499, duration_mins: 90, description: "Full styling, sanitary trim, nail clipping, and ear cleaning." }
    ]
  },

  // 4. TRAINING
  {
    id: "biz_train_blr_1",
    name: "K9 Champions Training Academy",
    businessName: "K9 Champions Training Academy",
    type: "training",
    status: "active",
    rating: 5.0,
    reviews_count: 210,
    reviewCount: 210,
    price_per_night: 1999,
    price_from: 1999,
    base_rate_per_day: 1999,
    priceFrom: 1999,
    address: "27th Main Rd, Sector 1, HSR Layout, Bangalore, Karnataka 560102",
    city: "Bangalore",
    lat: 12.9121,
    lng: 77.6446,
    latitude: 12.9121,
    longitude: 77.6446,
    phone: "+91 98455 12345",
    contact_phone: "+91 98455 12345",
    email: "coach@k9champions.in",
    contact_email: "coach@k9champions.in",
    owner_id: "NsfsgoFIozLMldH1KBGqTlZWeDw2",
    capacity: 30,
    open24Hours: false,
    verified: true,
    created_at: new Date(Date.now() - 86400000 * 25).toISOString(),
    description: "Certified canine behaviorists and agility trainers offering positive reinforcement puppy obedience, leash reactivity correction, socialization classes, and therapy dog preparation.",
    image_url: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&q=80&w=1000",
    images: [
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&q=80&w=1000"
    ],
    services_offered: [
      { id: "puppy-training", name: "Puppy Starter Obedience Course", price: 1999, duration_mins: 60, description: "One-on-one session covering potty training, bite inhibition, and basic sit/stay commands." },
      { id: "behaviour-training", name: "Behavior Modification & Leash Reactivity", price: 2999, duration_mins: 75, description: "Targeted intervention for anxiety, aggression, and excessive barking." },
      { id: "advanced-commands", name: "Off-Leash Advanced Agility", price: 3499, duration_mins: 90, description: "Advanced obstacle navigation and recall mastery under distraction." }
    ]
  },
  {
    id: "biz_train_mum_1",
    name: "Smart Paws Behaviour & Agility Clinic",
    businessName: "Smart Paws Behaviour & Agility Clinic",
    type: "training",
    status: "active",
    rating: 4.9,
    reviews_count: 165,
    reviewCount: 165,
    price_per_night: 2499,
    price_from: 2499,
    base_rate_per_day: 2499,
    priceFrom: 2499,
    address: "Hiranandani Gardens, Powai, Mumbai, Maharashtra 400076",
    city: "Mumbai",
    lat: 19.1176,
    lng: 72.9060,
    latitude: 19.1176,
    longitude: 72.9060,
    phone: "+91 98205 67890",
    contact_phone: "+91 98205 67890",
    email: "info@smartpawsmumbai.com",
    contact_email: "info@smartpawsmumbai.com",
    owner_id: "NsfsgoFIozLMldH1KBGqTlZWeDw2",
    capacity: 25,
    open24Hours: false,
    verified: true,
    created_at: new Date(Date.now() - 86400000 * 19).toISOString(),
    description: "Mumbai's premier positive-reinforcement training center. We transform naughty pups into well-mannered companions through fun games and reward-based cognitive coaching.",
    image_url: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&q=80&w=1000",
    images: [
      "https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&q=80&w=1000"
    ],
    services_offered: [
      { id: "obedience-training", name: "1-on-1 Obedience Training", price: 2499, duration_mins: 60, description: "Custom tailored behavioral coaching session at our training arena or your residence." },
      { id: "potty-training", name: "Housebreaking & Potty Training Mastery", price: 1799, duration_mins: 45, description: "Proven step-by-step guidance for seamless home crate and potty habits." }
    ]
  },

  // 5. DAYCARE
  {
    id: "biz_daycare_blr_1",
    name: "Happy Tails Daycare & Pool Park",
    businessName: "Happy Tails Daycare & Pool Park",
    type: "daycare",
    status: "active",
    rating: 4.9,
    reviews_count: 195,
    reviewCount: 195,
    price_per_night: 699,
    price_from: 699,
    base_rate_per_day: 699,
    priceFrom: 699,
    address: "24th Main Rd, JP Nagar 6th Phase, Bangalore, Karnataka 560078",
    city: "Bangalore",
    lat: 12.9063,
    lng: 77.5857,
    latitude: 12.9063,
    longitude: 77.5857,
    phone: "+91 98450 99887",
    contact_phone: "+91 98450 99887",
    email: "play@happytailsdaycare.in",
    contact_email: "play@happytailsdaycare.in",
    owner_id: "NsfsgoFIozLMldH1KBGqTlZWeDw2",
    capacity: 40,
    open24Hours: false,
    verified: true,
    created_at: new Date(Date.now() - 86400000 * 27).toISOString(),
    description: "A fun-filled daytime paradise for your dogs while you work! Featuring a bone-shaped splash pool, shaded turf play yards, nap cubbies, and continuous human supervision.",
    image_url: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&q=80&w=1000",
    images: [
      "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&q=80&w=1000"
    ],
    services_offered: [
      { id: "full-day-care", name: "Full Day Play & Care (8 Hours)", price: 699, duration_mins: 480, description: "Includes group play, pool access, afternoon nap time, and organic snacks." },
      { id: "half-day-care", name: "Half Day Play Pass (4 Hours)", price: 449, duration_mins: 240, description: "Perfect for morning or afternoon socialization and energy burning." }
    ]
  },
  {
    id: "biz_daycare_pune_1",
    name: "Sunnyside Pet Daycare & Playland",
    businessName: "Sunnyside Pet Daycare & Playland",
    type: "daycare",
    status: "active",
    rating: 4.8,
    reviews_count: 130,
    reviewCount: 130,
    price_per_night: 599,
    price_from: 599,
    base_rate_per_day: 599,
    priceFrom: 599,
    address: "East Avenue, Kalyani Nagar, Pune, Maharashtra 411006",
    city: "Pune",
    lat: 18.5463,
    lng: 73.9030,
    latitude: 18.5463,
    longitude: 73.9030,
    phone: "+91 98222 33445",
    contact_phone: "+91 98222 33445",
    email: "hello@sunnysidepune.in",
    contact_email: "hello@sunnysidepune.in",
    owner_id: "NsfsgoFIozLMldH1KBGqTlZWeDw2",
    capacity: 25,
    open24Hours: false,
    verified: true,
    created_at: new Date(Date.now() - 86400000 * 14).toISOString(),
    description: "Pune's premier indoor/outdoor pet playground. We group dogs by size and temperament for safe, exhilarating play supervised by certified canine behavior enthusiasts.",
    image_url: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&q=80&w=1000",
    images: [
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&q=80&w=1000"
    ],
    services_offered: [
      { id: "full-day-care", name: "Full Day Socialization Pass", price: 599, duration_mins: 480, description: "Complete day of supervised group play, toys, and rest sessions." },
      { id: "hourly-care", name: "Hourly Drop-in Play", price: 199, duration_mins: 60, description: "Flexible hourly childcare for your pets while you run errands." }
    ]
  },

  // 6. WALKING
  {
    id: "biz_walking_blr_1",
    name: "Step & Bark Professional Dog Walkers",
    businessName: "Step & Bark Professional Dog Walkers",
    type: "walking",
    status: "active",
    rating: 4.9,
    reviews_count: 145,
    reviewCount: 145,
    price_per_night: 299,
    price_from: 299,
    base_rate_per_day: 299,
    priceFrom: 299,
    address: "100 Feet Road, Indiranagar, Bangalore, Karnataka 560038",
    city: "Bangalore",
    lat: 12.9719,
    lng: 77.6412,
    latitude: 12.9719,
    longitude: 77.6412,
    phone: "+91 98451 00011",
    contact_phone: "+91 98451 00011",
    email: "walks@stepandbark.com",
    contact_email: "walks@stepandbark.com",
    owner_id: "NsfsgoFIozLMldH1KBGqTlZWeDw2",
    capacity: 50,
    open24Hours: false,
    verified: true,
    created_at: new Date(Date.now() - 86400000 * 22).toISOString(),
    description: "Reliable, GPS-tracked dog walking services by trained handlers. Receive live route maps, pee/poop notifications, and photos after every walk!",
    image_url: "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=1000",
    images: [
      "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=1000"
    ],
    services_offered: [
      { id: "individual-walk", name: "30-Min Solo Neighborhood Walk", price: 299, duration_mins: 30, description: "Dedicated 1-on-1 exercise walk tailored to your dog's pace with live GPS tracking." },
      { id: "long-walk", name: "60-Min Power Exercise Walk", price: 499, duration_mins: 60, description: "Extended cardio walk for high-energy breeds with fresh water stops." }
    ]
  },

  // 7. TAXI
  {
    id: "biz_taxi_mum_1",
    name: "SafePaws Express Pet Taxi & Ambulance",
    businessName: "SafePaws Express Pet Taxi & Ambulance",
    type: "taxi",
    status: "active",
    rating: 4.9,
    reviews_count: 178,
    reviewCount: 178,
    price_per_night: 499,
    price_from: 499,
    base_rate_per_day: 499,
    priceFrom: 499,
    address: "Sahar Road, Andheri East, Mumbai, Maharashtra 400099",
    city: "Mumbai",
    lat: 19.1136,
    lng: 72.8697,
    latitude: 19.1136,
    longitude: 72.8697,
    phone: "+91 98201 99988",
    contact_phone: "+91 98201 99988",
    email: "dispatch@safepawstaxi.in",
    contact_email: "dispatch@safepawstaxi.in",
    owner_id: "NsfsgoFIozLMldH1KBGqTlZWeDw2",
    capacity: 20,
    open24Hours: true,
    verified: true,
    created_at: new Date(Date.now() - 86400000 * 29).toISOString(),
    description: "Mumbai's dedicated air-conditioned pet transit service. Fully sanitized SUV cabs equipped with safety harnesses, crates, ramps, and oxygen support for emergency vet transfers.",
    image_url: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&q=80&w=1000",
    images: [
      "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&q=80&w=1000"
    ],
    services_offered: [
      { id: "vet-transport", name: "Vet Clinic Transfer (One Way)", price: 499, duration_mins: 45, description: "Safe pickup and drop to your veterinarian with driver assistance." },
      { id: "airport-drop", name: "Airport Terminal Drop / Pickup", price: 1499, duration_mins: 90, description: "Spacious luggage and crate transfer to Mumbai airport terminals." },
      { id: "emergency-pickup", name: "24/7 Emergency Ambulance Transit", price: 1999, duration_mins: 45, description: "Immediate priority dispatch with oxygen cylinders and stretcher support." }
    ]
  },

  // 8. SITTING
  {
    id: "biz_sitting_blr_1",
    name: "Cozy Home Pet Sitting & Nanny",
    businessName: "Cozy Home Pet Sitting & Nanny",
    type: "sitting",
    status: "active",
    rating: 5.0,
    reviews_count: 112,
    reviewCount: 112,
    price_per_night: 899,
    price_from: 899,
    base_rate_per_day: 899,
    priceFrom: 899,
    address: "5th Block, Koramangala, Bangalore, Karnataka 560095",
    city: "Bangalore",
    lat: 12.9360,
    lng: 77.6250,
    latitude: 12.9360,
    longitude: 77.6250,
    phone: "+91 98452 33221",
    contact_phone: "+91 98452 33221",
    email: "nanny@cozypetsitting.com",
    contact_email: "nanny@cozypetsitting.com",
    owner_id: "NsfsgoFIozLMldH1KBGqTlZWeDw2",
    capacity: 15,
    open24Hours: true,
    verified: true,
    created_at: new Date(Date.now() - 86400000 * 16).toISOString(),
    description: "Going on vacation? Keep your pets in the comfort of their own home! Our background-verified pet nannies provide in-home feeding, playtime, plant watering, and overnight stays.",
    image_url: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&q=80&w=1000",
    images: [
      "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&q=80&w=1000"
    ],
    services_offered: [
      { id: "home-visit", name: "60-Min Home Drop-In Visit", price: 499, duration_mins: 60, description: "Includes feeding, fresh water, litter cleaning, playtime, and photo update." },
      { id: "overnight-sitting", name: "12-Hour Overnight In-Home Nanny", price: 1499, duration_mins: 720, description: "Dedicated overnight stay in your home ensuring your pet is never lonely." }
    ]
  }
];

export const SEED_REVIEWS = [
  {
    id: "rev_1",
    business_id: "biz_boarding_blr_1",
    user_id: "customer_priya",
    user_name: "Priya Patel",
    rating: 5,
    comment: "Paws & Tail Resort is an absolute blessing! Left my Golden Retriever Simba here for 5 days while traveling to London. The 24/7 webcam feature gave me total peace of mind, and Simba came back so happy and clean after his complimentary bath!",
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    verified: true
  },
  {
    id: "rev_2",
    business_id: "biz_boarding_blr_1",
    user_id: "customer_rahul",
    user_name: "Rahul Verma",
    rating: 5,
    comment: "Best boarding facility in Bangalore! The play yards are huge, and the staff genuinely love animals. Dr. Sharma's team also did a quick dental checkup for Max. 10/10 recommended!",
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    verified: true
  },
  {
    id: "rev_3",
    business_id: "biz_vet_blr_1",
    user_id: "customer_priya",
    user_name: "Priya Patel",
    rating: 5,
    comment: "Dr. Sharma is incredibly knowledgeable and empathetic. We rushed our cat Luna for a midnight emergency when she had an allergic reaction, and the ICU staff treated her immediately. Truly life-saving service!",
    created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
    verified: true
  },
  {
    id: "rev_4",
    business_id: "biz_groom_blr_1",
    user_id: "customer_rahul",
    user_name: "Rahul Verma",
    rating: 5,
    comment: "Anita's grooming studio is fantastic! They handled my German Shepherd's shedding so professionally. His coat has never felt softer or smelled better!",
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    verified: true
  }
];

export const SEED_BOOKINGS = [
  {
    id: "bkg_demo_1",
    booking_id: "bkg_demo_1",
    business_id: "biz_boarding_blr_1",
    businessName: "Paws & Tail Luxury Pet Resort",
    customer_id: {
      id: "customer_priya",
      full_name: "Priya Patel",
      email: "priya.patel@gmail.com",
      phone: "+91 98765 33333"
    },
    customerId: "customer_priya",
    partnerId: "NsfsgoFIozLMldH1KBGqTlZWeDw2",
    pet_names: "Simba",
    pet_count: 1,
    service_name: "Deluxe AC Room",
    check_in: new Date(Date.now() + 86400000 * 2).toISOString(),
    check_out: new Date(Date.now() + 86400000 * 5).toISOString(),
    status: "confirmed",
    total_amount: 4497,
    payment_status: "paid",
    created_at: new Date(Date.now() - 86400000 * 1).toISOString()
  },
  {
    id: "bkg_demo_2",
    booking_id: "bkg_demo_2",
    business_id: "biz_vet_blr_1",
    businessName: "Gouuji 24/7 Speciality Vet Hospital",
    customer_id: {
      id: "customer_rahul",
      full_name: "Rahul Verma",
      email: "rahul.verma@gmail.com",
      phone: "+91 98765 44444"
    },
    customerId: "customer_rahul",
    partnerId: "partner_dr_sharma",
    pet_names: "Max",
    pet_count: 1,
    service_name: "General Checkup & Consultation",
    check_in: new Date().toISOString(),
    check_out: new Date(Date.now() + 3600000).toISOString(),
    status: "checked_in",
    total_amount: 799,
    payment_status: "paid",
    created_at: new Date(Date.now() - 3600000 * 2).toISOString()
  }
];
