import {
  Home, Stethoscope, Scissors, GraduationCap, Car, Footprints,
  Sun, Dog, HeartPulse, Star, UtensilsCrossed, Gamepad2,
  Video, Ambulance, ShoppingBag, Crown, Shield, PawPrint,
  Flower2, PartyPopper, Thermometer, Syringe, Microscope,
  Sparkles, Bath, Dumbbell, BriefcaseMedical, Apple, Music
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export interface SubService {
  id: string;
  name: string;
}

export interface ServiceCategory {
  id: string;
  name: string;
  icon: LucideIcon;
  color: string;          // Tailwind bg + text
  bgGradient: string;     // card background gradient
  borderColor: string;    // border color class
  description: string;
  subServices: SubService[];
  phase: 1 | 2;          // 1 = MVP, 2 = future
}

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: "boarding",
    name: "Pet Boarding",
    icon: Home,
    color: "bg-purple-100 text-purple-800",
    bgGradient: "from-purple-50/80 to-purple-100/60",
    borderColor: "border-purple-200",
    description: "Safe overnight stays in comfortable rooms for your pets.",
    phase: 1,
    subServices: [
      { id: "standard-room", name: "Standard Room" },
      { id: "deluxe-room", name: "Deluxe Room" },
      { id: "premium-room", name: "Premium Room" },
      { id: "luxury-suite", name: "Luxury Suite" },
      { id: "family-suite", name: "Family Suite (Multiple Pets)" },
      { id: "executive-suite", name: "Executive Suite" },
      { id: "ac-room", name: "AC Room" },
      { id: "non-ac-room", name: "Non-AC Room" },
      { id: "day-boarding", name: "Day Boarding" },
      { id: "overnight-boarding", name: "Overnight Boarding" },
      { id: "weekend-boarding", name: "Weekend Boarding" },
      { id: "weekly-boarding", name: "Weekly Boarding" },
      { id: "monthly-boarding", name: "Monthly Boarding" },
      { id: "holiday-boarding", name: "Holiday Boarding" },
      { id: "emergency-boarding", name: "Emergency Boarding" },
    ],
  },
  {
    id: "veterinary",
    name: "Veterinary",
    icon: Stethoscope,
    color: "bg-purple-100 text-purple-800",
    bgGradient: "from-purple-50/80 to-purple-100/60",
    borderColor: "border-purple-200",
    description: "Professional medical care, vaccinations, and diagnostics.",
    phase: 1,
    subServices: [
      { id: "general-checkup", name: "General Check-up" },
      { id: "puppy-checkup", name: "Puppy/Kitten Check-up" },
      { id: "senior-checkup", name: "Senior Pet Check-up" },
      { id: "emergency-consult", name: "Emergency Consultation" },
      { id: "online-consult", name: "Online Consultation" },
      { id: "rabies-vaccine", name: "Rabies Vaccination" },
      { id: "dhpp-vaccine", name: "DHPP Vaccination" },
      { id: "kennel-cough", name: "Kennel Cough Vaccine" },
      { id: "deworming", name: "Deworming" },
      { id: "tick-flea", name: "Tick & Flea Treatment" },
      { id: "dental-care", name: "Dental Care" },
      { id: "surgery", name: "Surgery" },
      { id: "blood-test", name: "Blood Test" },
      { id: "x-ray", name: "X-Ray" },
      { id: "ultrasound", name: "Ultrasound" },
      { id: "microchipping", name: "Microchipping" },
      { id: "health-certificate", name: "Health Certificate" },
      { id: "sterilization", name: "Sterilization" },
    ],
  },
  {
    id: "grooming",
    name: "Pet Grooming",
    icon: Scissors,
    color: "bg-purple-100 text-purple-800",
    bgGradient: "from-purple-50/80 to-purple-100/60",
    borderColor: "border-purple-200",
    description: "Bathing, trimming, styling, and full spa treatments.",
    phase: 1,
    subServices: [
      { id: "basic-bath", name: "Basic Bath" },
      { id: "medicated-bath", name: "Medicated Bath" },
      { id: "flea-bath", name: "Flea Bath" },
      { id: "herbal-bath", name: "Herbal Bath" },
      { id: "hair-trimming", name: "Hair Trimming" },
      { id: "hair-styling", name: "Hair Styling" },
      { id: "breed-grooming", name: "Breed-Specific Grooming" },
      { id: "nail-trimming", name: "Nail Trimming" },
      { id: "ear-cleaning", name: "Ear Cleaning" },
      { id: "teeth-cleaning", name: "Teeth Cleaning" },
      { id: "eye-cleaning", name: "Eye Cleaning" },
      { id: "spa-treatment", name: "Spa Treatment" },
      { id: "aromatherapy", name: "Aromatherapy" },
      { id: "massage", name: "Massage" },
      { id: "paw-treatment", name: "Paw Treatment" },
      { id: "deshedding", name: "De-shedding" },
      { id: "perfume-spray", name: "Perfume Spray" },
    ],
  },
  {
    id: "training",
    name: "Pet Training",
    icon: GraduationCap,
    color: "bg-purple-100 text-purple-800",
    bgGradient: "from-purple-50/80 to-purple-100/60",
    borderColor: "border-purple-200",
    description: "Obedience, behaviour, and advanced command training.",
    phase: 1,
    subServices: [
      { id: "obedience-training", name: "Obedience Training" },
      { id: "puppy-training", name: "Puppy Training" },
      { id: "behaviour-training", name: "Behaviour Training" },
      { id: "aggression-control", name: "Aggression Control" },
      { id: "potty-training", name: "Potty Training" },
      { id: "leash-training", name: "Leash Training" },
      { id: "socialization", name: "Socialization Training" },
      { id: "advanced-commands", name: "Advanced Commands" },
      { id: "therapy-dog", name: "Therapy Dog Training" },
    ],
  },
  {
    id: "taxi",
    name: "Pet Taxi",
    icon: Car,
    color: "bg-purple-100 text-purple-800",
    bgGradient: "from-purple-50/80 to-purple-100/60",
    borderColor: "border-purple-200",
    description: "Safe pet pickup and drop-off transportation services.",
    phase: 1,
    subServices: [
      { id: "home-pickup", name: "Home Pickup" },
      { id: "home-drop", name: "Home Drop" },
      { id: "airport-pickup", name: "Airport Pickup" },
      { id: "airport-drop", name: "Airport Drop" },
      { id: "vet-transport", name: "Vet Transportation" },
      { id: "emergency-pickup", name: "Emergency Pickup" },
      { id: "grooming-pickup", name: "Grooming Pickup" },
      { id: "boarding-pickup", name: "Boarding Pickup" },
    ],
  },
  {
    id: "walking",
    name: "Pet Walking",
    icon: Footprints,
    color: "bg-purple-100 text-purple-800",
    bgGradient: "from-purple-50/80 to-purple-100/60",
    borderColor: "border-purple-200",
    description: "Daily walks and outdoor exercise by professional walkers.",
    phase: 1,
    subServices: [
      { id: "morning-walk", name: "Morning Walk" },
      { id: "evening-walk", name: "Evening Walk" },
      { id: "long-walk", name: "Long Walk" },
      { id: "group-walk", name: "Group Walk" },
      { id: "individual-walk", name: "Individual Walk" },
    ],
  },
  {
    id: "daycare",
    name: "Pet Day Care",
    icon: Sun,
    color: "bg-purple-100 text-purple-800",
    bgGradient: "from-purple-50/80 to-purple-100/60",
    borderColor: "border-purple-200",
    description: "Supervised daytime care with play, activities, and feeding.",
    phase: 1,
    subServices: [
      { id: "half-day-care", name: "Half-Day Care" },
      { id: "full-day-care", name: "Full-Day Care" },
      { id: "hourly-care", name: "Hourly Day Care" },
      { id: "weekend-daycare", name: "Weekend Day Care" },
    ],
  },
  {
    id: "sitting",
    name: "Pet Sitting",
    icon: Dog,
    color: "bg-purple-100 text-purple-800",
    bgGradient: "from-purple-50/80 to-purple-100/60",
    borderColor: "border-purple-200",
    description: "In-home or facility-based pet sitting with dedicated care.",
    phase: 1,
    subServices: [
      { id: "home-visit", name: "Home Visit" },
      { id: "overnight-sitting", name: "Overnight Sitting" },
      { id: "holiday-sitting", name: "Holiday Sitting" },
    ],
  },
  {
    id: "health-monitoring",
    name: "Health Monitoring",
    icon: HeartPulse,
    color: "bg-purple-100 text-purple-800",
    bgGradient: "from-purple-50/80 to-purple-100/60",
    borderColor: "border-purple-200",
    description: "Real-time tracking of weight, vitals, medication, and activity.",
    phase: 1,
    subServices: [
      { id: "weight-tracking", name: "Weight Monitoring" },
      { id: "temperature-check", name: "Temperature Tracking" },
      { id: "water-intake", name: "Water Intake Log" },
      { id: "food-intake", name: "Food Intake Log" },
      { id: "medication-log", name: "Medication Log" },
      { id: "exercise-log", name: "Exercise Log" },
      { id: "behaviour-log", name: "Behaviour Monitoring" },
      { id: "sleep-log", name: "Sleep Monitoring" },
    ],
  },
  {
    id: "special-care",
    name: "Special Care",
    icon: Star,
    color: "bg-purple-100 text-purple-800",
    bgGradient: "from-purple-50/80 to-purple-100/60",
    borderColor: "border-purple-200",
    description: "Specialized care for senior, disabled, or post-surgery pets.",
    phase: 1,
    subServices: [
      { id: "senior-care", name: "Senior Pet Care" },
      { id: "disabled-care", name: "Disabled Pet Care" },
      { id: "special-diet", name: "Special Diet" },
      { id: "post-surgery-care", name: "Post-Surgery Care" },
      { id: "medical-observation", name: "Medical Observation" },
      { id: "isolation-room", name: "Isolation Room" },
    ],
  },
  {
    id: "food",
    name: "Food Services",
    icon: UtensilsCrossed,
    color: "bg-purple-100 text-purple-800",
    bgGradient: "from-purple-50/80 to-purple-100/60",
    borderColor: "border-purple-200",
    description: "Custom meals, prescription diets, and premium pet food.",
    phase: 1,
    subServices: [
      { id: "standard-food", name: "Standard Food" },
      { id: "premium-food", name: "Premium Food" },
      { id: "wet-food", name: "Wet Food" },
      { id: "dry-food", name: "Dry Food" },
      { id: "homemade-food", name: "Homemade Food" },
      { id: "prescription-diet", name: "Prescription Diet" },
      { id: "custom-diet", name: "Custom Diet" },
    ],
  },
  {
    id: "activities",
    name: "Activities",
    icon: Gamepad2,
    color: "bg-purple-100 text-purple-800",
    bgGradient: "from-purple-50/80 to-purple-100/60",
    borderColor: "border-purple-200",
    description: "Play areas, swimming, agility, and social activities.",
    phase: 2,
    subServices: [
      { id: "play-area", name: "Play Area" },
      { id: "swimming", name: "Swimming" },
      { id: "agility-training", name: "Agility Training" },
      { id: "ball-games", name: "Ball Games" },
      { id: "social-play", name: "Social Play" },
      { id: "indoor-games", name: "Indoor Games" },
    ],
  },
  {
    id: "live-monitoring",
    name: "Live Monitoring",
    icon: Video,
    color: "bg-purple-100 text-purple-800",
    bgGradient: "from-purple-50/80 to-purple-100/60",
    borderColor: "border-purple-200",
    description: "CCTV live streaming, photos, and videos during boarding.",
    phase: 2,
    subServices: [
      { id: "cctv-live", name: "CCTV Live Stream" },
      { id: "daily-photos", name: "Daily Photos" },
      { id: "daily-videos", name: "Daily Videos" },
      { id: "live-chat", name: "Live Chat with Caretaker" },
    ],
  },
  {
    id: "emergency",
    name: "Emergency Care",
    icon: Ambulance,
    color: "bg-purple-100 text-purple-800",
    bgGradient: "from-purple-50/80 to-purple-100/60",
    borderColor: "border-purple-200",
    description: "24/7 emergency vet, pickup, and ICU monitoring services.",
    phase: 2,
    subServices: [
      { id: "emergency-vet", name: "Emergency Vet" },
      { id: "emergency-pickup-24", name: "Emergency Pickup" },
      { id: "overnight-medical", name: "Overnight Medical Care" },
      { id: "icu-monitoring", name: "ICU Monitoring" },
    ],
  },
  {
    id: "shop",
    name: "Pet Shop",
    icon: ShoppingBag,
    color: "bg-purple-100 text-purple-800",
    bgGradient: "from-purple-50/80 to-purple-100/60",
    borderColor: "border-purple-200",
    description: "Food, accessories, medicines, and pet care products.",
    phase: 2,
    subServices: [
      { id: "dry-food-shop", name: "Dry Food" },
      { id: "wet-food-shop", name: "Wet Food" },
      { id: "treats", name: "Treats" },
      { id: "collars", name: "Collars & Leashes" },
      { id: "toys", name: "Toys" },
      { id: "beds", name: "Beds" },
      { id: "medicines", name: "Medicines" },
      { id: "supplements", name: "Supplements" },
      { id: "shampoos", name: "Shampoos" },
    ],
  },
  {
    id: "membership",
    name: "Memberships",
    icon: Crown,
    color: "bg-purple-100 text-purple-800",
    bgGradient: "from-purple-50/80 to-purple-100/60",
    borderColor: "border-purple-200",
    description: "Silver, Gold & Platinum plans with exclusive benefits.",
    phase: 2,
    subServices: [
      { id: "silver-plan", name: "Silver Plan" },
      { id: "gold-plan", name: "Gold Plan" },
      { id: "platinum-plan", name: "Platinum Plan" },
    ],
  },
  {
    id: "insurance",
    name: "Pet Insurance",
    icon: Shield,
    color: "bg-purple-100 text-purple-800",
    bgGradient: "from-purple-50/80 to-purple-100/60",
    borderColor: "border-purple-200",
    description: "Insurance registration, claim assistance, and policy renewal.",
    phase: 2,
    subServices: [
      { id: "insurance-reg", name: "Insurance Registration" },
      { id: "claim-assist", name: "Claim Assistance" },
      { id: "policy-renewal", name: "Policy Renewal" },
    ],
  },
  {
    id: "adoption",
    name: "Adoption",
    icon: PawPrint,
    color: "bg-purple-100 text-purple-800",
    bgGradient: "from-purple-50/80 to-purple-100/60",
    borderColor: "border-purple-200",
    description: "Find loving homes for rescued and shelter pets.",
    phase: 2,
    subServices: [
      { id: "adopt-dog", name: "Adopt a Dog" },
      { id: "adopt-cat", name: "Adopt a Cat" },
      { id: "adopt-other", name: "Adopt Other Pets" },
    ],
  },
  {
    id: "breeding",
    name: "Breeding",
    icon: Flower2,
    color: "bg-purple-100 text-purple-800",
    bgGradient: "from-purple-50/80 to-purple-100/60",
    borderColor: "border-purple-200",
    description: "Stud services and professional breeding consultations.",
    phase: 2,
    subServices: [
      { id: "stud-service", name: "Stud Service" },
      { id: "breeding-consult", name: "Breeding Consultation" },
    ],
  },
  {
    id: "events",
    name: "Pet Events",
    icon: PartyPopper,
    color: "bg-purple-100 text-purple-800",
    bgGradient: "from-purple-50/80 to-purple-100/60",
    borderColor: "border-purple-200",
    description: "Birthday parties, photoshoots, training camps, and competitions.",
    phase: 2,
    subServices: [
      { id: "birthday-party", name: "Pet Birthday Party" },
      { id: "photoshoot", name: "Pet Photoshoot" },
      { id: "training-camp", name: "Training Camp" },
      { id: "competitions", name: "Competitions" },
    ],
  },
];

/** All 20 categories */
export const ALL_CATEGORIES = SERVICE_CATEGORIES;

/** MVP Phase 1 categories (first 11) */
export const MVP_CATEGORIES = SERVICE_CATEGORIES.filter(c => c.phase === 1);

/** Get a category by its id */
export const getCategoryById = (id: string): ServiceCategory | undefined =>
  SERVICE_CATEGORIES.find(c => c.id === id);

/** All unique category IDs for partner dropdown */
export const CATEGORY_IDS = SERVICE_CATEGORIES.map(c => c.id);

/** Category names keyed by id */
export const CATEGORY_NAMES: Record<string, string> = Object.fromEntries(
  SERVICE_CATEGORIES.map(c => [c.id, c.name])
);

